---
title: "Conjunction Error Analysis"
author: "Jonathan Rystrøm"
date: '2022-08-18'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse, fs)
```
```{r}
read_with_name <- function(f, raw_dat) {
  read_csv(f) %>% 
    mutate(fname = f,
           prompt = raw_dat$prompt) 
}
```

```{r}
raw_data <- read_csv("data/conjunction.csv")
result_files <- fs::dir_ls("results/conjunction", glob="*.csv")
results <- map_dfr(result_files, ~read_with_name(.x, raw_data))
results

```
## Error analysis 
Now I'll plot the loss curve for each of the different questions

```{r}
plot_results <- results %>% 
  mutate(prompt_type = str_extract(prompt, "oil rig|bank teller|accountant|librarian"), 
         model = str_extract(fname, "ada|babbage|curie|davinci"))

plot_results %>% 
  ggplot(aes(x=model, y=logodds_difference)) + 
  geom_violin() + 
  facet_wrap(~prompt_type) + 
  theme_minimal() + 
  labs(title = "Error analysis of different conjunction prompts")
```

